### PR TITLE
built php 7.0.1, no ini file though

### PR DESCRIPTION
**Pull request by rscorer**
compiled 7.0.1 - no ini files though. not sure of changes needed.

### CODE REVIEW

**Comment by boekkooi** [comment]
Great job @rscorer can you include the default .ini for now?

**Comment by rscorer** [comment]
Will try this weekend - not sure how to turn .ini to .erb but will investigate :)

**Comment by boekkooi** [comment]
Well [erb](https://access.redhat.com/documentation/en-US/OpenShift_Online/2.0/html/Cartridge_Specification_Guide/chap-Using_Cartridge_Scripts.html#ERB_Processing1) is a very simple templating language. It just reads a file until it finds `<%=` and then it will inject that (environment) value.

So the only changes you need to make to the ini (i think) are:

```
error_log = <%= ENV['OPENSHIFT_LOG_DIR'] %>/php-error.log
extension_dir = "<%= ENV['OPENSHIFT_PHP_EXTENSION_DIR'] %>"
session.save_path = "<%= ENV['OPENSHIFT_TMP_DIR'] %>"
```

and that's it.

The only problem left then is that we should rename the php.ini.erb to something like php-{version}.ini.erb since else we can only support PHP 7. 
For this we need to change [control](https://github.com/boekkooi/openshift-cartridge-php/blob/master/bin/control#L36) and manually place `PHPRC` (aka remove [PHPRC.erb](https://github.com/boekkooi/openshift-cartridge-php/blob/master/env/PHPRC.erb) and set it in [setup](https://github.com/boekkooi/openshift-cartridge-php/blob/master/bin/setup#L34))

But thank you for this PR if you don't have the time then I will take a look at it when I get some free time.

**Comment by rscorer** [comment]
Oh cool, I'll give that a try :)
I was wondering about renaming the ini, will look at that too!

**Comment by rscorer** [comment]
sorry, terrible weekend - had no time for checking into this. hopefully can try during the week. 

frustratingly so close!

**Comment by boekkooi** [comment]
No problem! Your almost there and this will be a great PR :smile:

**Comment by vs0uz4** [comment]
@rscorer 

you compiled version or got from somewhere already compiled?

is compiled, you tell if something has changed in the settings of issues at compile time (./configure)?

**Comment by boekkooi** [comment]
I'm closing this since php 7.0.7 is now available in master

**Pull request closed without merging**
